export const texts = {
  es: {
    manifesto: "Creando experiencias web",
    contact: "Contacto",
    notaManifiesto: "Manifiesto",
    notaProyectos: "Proyectos",
    notaSoluciones: "Soluciones",
    notaStack: "Stack técnico",
    notaSobreMi: "Sobre mí",
    notaContacto: "Contacto",
    manifiestoTitulo: "Manifiesto",
    manifiestoFrase: "No diseño interfaces. Escribo atmósferas editoriales navegables.",
    manifiestoParrafo1:
      "Cada proyecto es una obra narrativa: estructura, ritmo, identidad. Cada decisión visual y técnica responde a una intención. No hay parches. No hay adornos. Hay síntesis.",
    manifiestoParrafo2:
      "Trabajo con precisión modular, control total y respeto por el tiempo. Valido cada ícono, cada línea, cada transición. Lo que no aporta atmósfera, sobra.",
    manifiestoParrafo3:
      "Mi portfolio no muestra lo que sé hacer. Muestra cómo pienso, cómo decido, cómo construyo.",
    manifiestoCierre: "Este manifiesto no se lee. Se respira.",
    recentProjectsTitulo: "Proyectos recientes",
    galeriaCrypto: "Cotizá Criptos",
    galeriaBitcoin: "Cotizá Bitcoins",
    galeriaOutfits: "Publicitá tus Productos",
    galeriaCheckit: "Chequeá Info",
    galeriaDolar: "Cotizá Dólar",
    galeriaMonedas: "Cotizá Monedas",
    galeriaSite: "Armá tu Sitio Web",
    solucionesTitulo: "Soluciones Creativas",
    solucionesTitulo: "Soluciones Creativas",
    case01Title: "Publicidad",
    case01Dilema: "Mi cliente tenía productos publicados en marketplaces pero no eran visitados y no podía costear publicidad.",
    case01Quote: "¡No ven mis artículos y la publicidad es muy cara!",
    case01Solucion: "Diseñé una interfaz web que reuniera los artículos, linkeando cada uno. Alojamiento gratuito, funcionalidad multiplataforma y estética cuidada.",
    case02Title: "Copywriting",
    case02Dilema: "Mi cliente tenía ideas narrativas profundas, pero no sabía cómo articularlas.",
    case02Quote: "¡Quiero contar muchas cosas, pero no sé cómo escribirlas!",
    case02Solucion: "Organizamos sus ideas, trabajamos juntas los textos, y construimos un blog, edición ebook y prefigurado de edición impresa.",
    case03Title: "Diseño Web",
    case03Dilema: "Mi cliente tenía un sitio creado por interfaz visual pero no reflejaba su identidad ni era funcional.",
    case03Quote: "¡Esta página no habla de mí y ya perdí mucho tiempo!",
    case03Solucion: "Rediseñamos identidad, hicimos ajustes estéticos y agregamos login tunizado para crear base de datos profesional.",
    caseSolucionTitle: "Solución",
    stackTitle: "Stack Técnico",
    aboutTitle: "Sobre mí",
    aboutText1: "Soy desarrolladora web y creadora digital con enfoque editorial. Mi proceso es iterativo, técnico y profundamente visual.",
    aboutText2: "Cada obra que desarrollo articula identidad, atmósfera y estructura.",
    aboutText3: "Consciente de la importancia de la información, la tecnología y la comunicación, he iniciado el estudio y divulgación de conceptos, herramientas y prácticas dentro del amplio campo de las TICs. Comienzo por lenguajes de programación, y exploro los itinerarios de la inteligencia artificial y ciencia de datos, descubriendo a cada paso lo apasionante e imprescindible de este espectro.",
    aboutSkillsTitle: "inborn Skills",
    aboutSkillsList: ["Proactividad", "Rendimiento bajo presión", "Vocación de consenso", "Capacidad de aprendizaje"],
    contactoTitulo: "Contacto",
    contactoPlaceholderNombre: "Tu nombre",
    contactoPlaceholderEmail: "Tu email",
    contactoPlaceholderMensaje: "Escribí tu mensaje",
    contactoBotonEnviar: "Enviar",
    contactoConfirmacion: "Mensaje enviado correctamente. ¡Gracias!",
    contactoError: "Ups... algo falló al enviar. Intentá de nuevo.",
    footer: "© {year} AnaSposito · Diseñadora digital · Narrativa web editorial · Sft Arch Composer"
    // ...
  },
  en: {
    manifesto: "Creating web experiences",
    contact: "Contact",
    notaManifiesto: "Manifesto",
    notaProyectos: "Projects",
    notaSoluciones: "Solutions",
    notaStack: "Tech Stack",
    notaSobreMi: "About Me",
    notaContacto: "Contact",
    manifiestoTitulo: "Manifesto",
    manifiestoFrase: "I don't design interfaces. I write navigable editorial atmospheres.",
    manifiestoParrafo1:
      "Each project is a narrative piece: structure, rhythm, identity. Every visual and technical decision responds to an intention. No patches. No ornaments. Only synthesis.",
    manifiestoParrafo2:
      "I work with modular precision, full control, and respect for time. I validate every icon, every line, every transition. What doesn’t build atmosphere, is left out.",
    manifiestoParrafo3:
      "My portfolio doesn’t show what I can do. It shows how I think, how I decide, how I build.",
    manifiestoCierre: "This manifesto isn’t read. It’s breathed.",
    recentProjectsTitulo: "Recent Projects",
    galeriaCrypto: "Quote Cryptos",
    galeriaBitcoin: "Quote Bitcoins",
    galeriaOutfits: "Advertise Your Products",
    galeriaCheckit: "Check Info",
    galeriaDolar: "Quote Dollars",
    galeriaMonedas: "Quote Currencies",
    galeriaSite: "Build Your Website",
    solucionesTitulo: "Creative Solutions",
    solucionesTitulo: "Creative Solutions",
    case01Title: "Advertising",
    case01Dilema: "My client had products listed in marketplaces but couldn't afford ads and wasn't getting visits.",
    case01Quote: "No one sees my listings and ads are expensive!",
    case01Solucion: "I designed a web interface linking all the products. Free hosting, multi-platform functionality, and curated aesthetics.",
    case02Title: "Copywriting",
    case02Dilema: "My client had deep narrative ideas, but didn't know how to articulate them.",
    case02Quote: "I want to share so much, but I don't know how to write it!",
    case02Solucion: "We organized her ideas, shaped the texts together, and built a blog, ebook edition and draft for print.",
    case03Title: "Web Design",
    case03Dilema: "My client's site was built with a visual interface but didn’t reflect her identity and wasn’t functional.",
    case03Quote: "This page doesn’t speak for me and I’ve wasted so much time!",
    case03Solucion: "We redesigned the identity, refined aesthetics, and added a customized login to build a professional database.",
    caseSolucionTitle: "Solution",
    stackTitle: "Tech Stack",
    aboutTitle: "About Me",
    aboutText1: "I'm a web developer and digital creator with an editorial approach. My process is iterative, technical and deeply visual.",
    aboutText2: "Each piece I develop articulates identity, atmosphere and structure.",
    aboutText3: "Aware of the importance of information, technology and communication, I’ve begun studying and sharing concepts, tools and practices across the broad field of ICTs. I start with programming languages and explore the paths of AI and data science, discovering with each step how essential and fascinating this spectrum is.",
    aboutSkillsTitle: "inborn Skills",
    aboutSkillsList: ["Proactivity", "Performance under pressure", "Consensus-driven mindset", "Learning capacity"],
    contactoTitulo: "Contact",
    contactoPlaceholderNombre: "Your name",
    contactoPlaceholderEmail: "Your email",
    contactoPlaceholderMensaje: "Write your message",
    contactoBotonEnviar: "Send",
    contactoConfirmacion: "Message sent successfully. Thank you!",
    contactoError: "Oops... something went wrong. Try again.",
    footer: "© {year} Ana · Digital designer · Editorial web narrative · Sft Arch Composer"  
  }
};
